export interface Riesgo {
    riesgoId?: number,
    procesoId: number,
    codigo: string,
    nombre: string,
    descripcion: string,
    responsable: string,
    factorRiesgo: string,
    frecuencia: number,
    impacto: number,
    tipoEvento: string,
    tipoEvento2: string,
    fuenteRiesgo: string,
    estado: string,
    riesgoInherente?: number,
    frecuenciaResidual?: number,
    impactoResidual?: number,
    riesgoResidual?: number,
    subprocesoId?: number,
    nombreSubproceso?: string,
    nombreActividad?: string,
    nombreRI?: string,
    nombreRR?: string,
}
